rvm:           # list all the Rubies you want to test against
  - 2.3.0
services:
  - postgresql
script: 
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rspec spec/
before_script:
  - psql -c 'CREATE USER test_user' -U postgres
  - psql -c 'create database lunch_ordering_test' -U postgres
  - psql -c 'GRANT ALL privileges ON DATABASE lunch_ordering_test TO test_user' -U postgres